# Generated by Django 3.2.20 on 2023-07-15 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_location', models.CharField(max_length=255)),
                ('division', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../default_event_i89yt9', upload_to='images/')),
                ('level_filter', models.CharField(choices=[('level1', 'Level-1'), ('level2', 'Level-2'), ('level3', 'Level-3'), ('level4', 'Level-4'), ('level5', 'Level-5')], default='level1', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
