# Generated by Django 3.2.20 on 2023-07-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_match_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateField(default=models.DateField(auto_now_add=True)),
        ),
    ]
