# Generated by Django 3.2.20 on 2023-07-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_match_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='level_filter',
            field=models.CharField(choices=[('Level-1', 'Level-1'), ('Level-2', 'Level-2'), ('Level-3', 'Level-3'), ('Level-4', 'Level-4'), ('Level-5', 'Level-5')], default='level1', max_length=32),
        ),
    ]
