# Generated by Django 3.2.20 on 2023-07-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
