# Generated by Django 3.2.20 on 2023-08-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0002_gun_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gun',
            name='type',
            field=models.CharField(choices=[('Handgun', 'Handgun'), ('Rifle', 'Rifle')], default='handgun', max_length=32),
        ),
    ]
