# Generated by Django 3.2.20 on 2023-08-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0003_alter_gun_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gun',
            name='type',
            field=models.CharField(choices=[('Handgun', 'Handgun'), ('Rifle', 'Rifle')], default='Handgun', max_length=32),
        ),
    ]
