# Generated by Django 3.2.20 on 2023-08-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermessages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usermessage',
        ),
    ]
